name: Publish Artifacts

on:
  release:
    types: [created]
  push:
    branches:
      - release-*

jobs:
  metadata:
    name: "Calculate Metadata"
    runs-on: ubuntu-latest
    steps:
      - name: "Capture versioning metadata (snapshot)"
        id: snapshot_metadata
        if: contains(github.ref, 'refs/heads/')
        run: |
          RELEASE=$(echo "${{ github.ref }}" | cut -d- -f2 )
          echo "image_tag=${RELEASE}" >> "$GITHUB_OUTPUT"
          echo "release_version=${RELEASE}-SNAPSHOT" >> "$GITHUB_OUTPUT"
          echo "release_name=Prelease ${RELEASE}" >> "$GITHUB_OUTPUT"
          echo "release_tag=pre-${RELEASE}" >> "$GITHUB_OUTPUT"
          echo "prerelease=true" >> "$GITHUB_OUTPUT"

      - name: "Capture versioning metadata (release)"
        id: release_metadata
        if: "!contains(github.ref, 'refs/heads/')"
        run: |
          echo "image_tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          echo "release_version=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          echo "release_name=${{ github.event.release.name }}" >> "$GITHUB_OUTPUT"
          echo "release_tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          echo "prerelease=false" >> "$GITHUB_OUTPUT"

    # these outputs simply mush together the two variables because, depending on the path, one will be empty
    outputs:
      image_tag: ${{ steps.snapshot_metadata.outputs.image_tag }}${{ steps.release_metadata.outputs.image_tag }}
      release_version: ${{ steps.snapshot_metadata.outputs.release_version }}${{ steps.release_metadata.outputs.release_version }}
      release_name: ${{ steps.snapshot_metadata.outputs.release_name }}${{ steps.release_metadata.outputs.release_name }}
      release_tag: ${{ steps.snapshot_metadata.outputs.release_tag }}${{ steps.release_metadata.outputs.release_tag }}
      prerelease: ${{ steps.snapshot_metadata.outputs.prerelease }}${{ steps.release_metadata.outputs.prerelease }}

  manage_release:
    name: "Manage Release Instance"
    needs: [metadata]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Ensure Release"
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ needs.metadata.outputs.prerelease }}
          name: ${{ needs.metadata.outputs.release_name }}
          tag_name: ${{ needs.metadata.outputs.release_tag }}

      # use this step to overwrite body for links at the end
      - name: "Set pre-release body"
        if: contains(github.ref, 'refs/heads/')
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.metadata.outputs.release_name }}
          tag_name: ${{ needs.metadata.outputs.release_tag }}
          body: "[PRERELEASE]"

  test:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest
    needs: [metadata,manage_release]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Cache local Maven Repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set release version
        run: mvn -B versions:set -DnewVersion="${{ needs.metadata.outputs.release_version }}"

      - name: Test with Maven
        run: mvn -B test

  build:
    name: "Build Java Command Executable"
    runs-on: ubuntu-latest
    needs: [metadata, test]
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Cache local Maven Repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set release version
        run: mvn -B versions:set -DnewVersion="${{ needs.metadata.outputs.release_version }}"

      - name: Build with Maven
        run: mvn -B -DskipTests -Dbuild=cli package

      - name: 'Upload Executable JAR to Artifact Cache'
        uses: actions/upload-artifact@v4
        with:
          name: taverna-cmd-${{ needs.metadata.outputs.release_version }}-executable.jar
          path: taverna-cmd/target/taverna-cmd-${{ needs.metadata.outputs.release_version }}-executable.jar
          retention-days: 1

  build_native:
    name: "Build Native Executable Command"
    # build on all target os
    runs-on: ${{ matrix.os }}
    needs: [metadata, test]
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            native-asset-suffix: linux-amd64
            target-suffix: ""
          - os: windows-latest
            native-asset-suffix: windows-amd64.exe
            target-suffix: .exe
          - os: macos-latest
            native-asset-suffix: macos
            target-suffix: ""

    permissions:
      contents: read
      packages: write

    steps:
      # install GraalVM (mandrel) for native build
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'mandrel'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # windows: install msbuild tools for native compile
      - name: Add msbuild to PATH
        if: contains(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.0.2

      # windows: ensure that dev tools are added to path
      - name: Add toolkit to path
        if: contains(matrix.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1

      # ubuntu: install packages needed for graalvm native compile
      - name: Install additional packages
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get install -y zlib1g-dev

      - uses: actions/checkout@v4

      - name: Set release version
        run: mvn -B versions:set -DnewVersion="${{ needs.metadata.outputs.release_version }}"

      - name: Build with Maven
        run: |
          mvn -B -Dbuild=cli -DskipTests -Dnative package
          mv taverna-cmd/target/taverna-cmd${{ matrix.target-suffix }} taverna-cmd/target/taverna-cmd-${{ needs.metadata.outputs.release_version }}-${{ matrix.native-asset-suffix }}

      - name: 'Upload Binary Executable'
        uses: actions/upload-artifact@v4
        with:
          name: taverna-cmd-${{ needs.metadata.outputs.release_version }}-${{ matrix.native-asset-suffix }}
          path: taverna-cmd/target/taverna-cmd-${{ needs.metadata.outputs.release_version }}-${{ matrix.native-asset-suffix }}
          retention-days: 1

  build_native_operator:
    name: "Build Native Operator"
    # build on all target os
    runs-on: ubuntu-latest
    needs: [metadata, test]

    permissions:
      contents: read
      packages: write

    steps:
      # install GraalVM (mandrel) for native build
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'mandrel'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # windows: install msbuild tools for native compile
      - name: Add msbuild to PATH
        if: contains(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.0.2

      # ubuntu: install packages needed for graalvm native compile
      - name: Install additional packages
        run: sudo apt-get install -y zlib1g-dev

      - uses: actions/checkout@v4

      - name: Set release version
        run: mvn -B versions:set -DnewVersion="${{ needs.metadata.outputs.release_version }}"

      - name: Build with Maven
        run: |
          mvn -B -Dbuild=operator -DskipTests -Drevision="${{ github.event.release.tag_name }}" -DquarkusNative package

  update_release:
    name: "Add Artifacts to Github Release"
    outputs:
      artifact_attestation_url: ${{ steps.attestation.outputs.attestation-url }}
    runs-on: ubuntu-latest

    needs: [metadata, manage_release, build, build_native]

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v4

      - name: 'Download Artifacts from Cache'
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Generate checksums
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            artifacts/*/*

      - name: "Generate Attestation for Artifacts"
        id: attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            "artifacts/*/taverna*"
            checksum.txt

      - name: "Upload Artifact to Release"
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.manage_release.outputs.release_name }}
          tag_name: ${{ needs.metadata.outputs.release_tag }}
          files: |
            artifacts/*/*
            checksum.txt
            ${{ steps.attestation.outputs.bundle-path }}

  container_image:
    name: "Build and Publish Command Container Image"
    runs-on: ubuntu-latest
    needs: [metadata, build_native]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    outputs:
      image_digest: ${{ steps.push.outputs.digest }}
      image_attestation_url: ${{ steps.attestation.outputs.attestation-url }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Download Artifact from Cache'
        uses: actions/download-artifact@v4
        with:
          name: taverna-cmd-${{ needs.metadata.outputs.release_version }}-linux-amd64
          path: taverna-cmd/target/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and Push Container Image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: taverna-cmd
          file: taverna-cmd/src/main/container/Dockerfile
          push: true
          tags: | 
            docker.io/chrisruffalo/taverna:${{ needs.metadata.outputs.image_tag }}
            quay.io/chrisruffalo/taverna:${{ needs.metadata.outputs.image_tag }}
          build-args: |
            INPUT_BINARY="taverna-cmd-${{ needs.metadata.outputs.release_version }}-linux-amd64"
            VERSION="${{ needs.metadata.outputs.image_tag }}"
            FULL_VERSION="${{ needs.metadata.outputs.release_version }}"
            GIT_HASH="${{ github.sha }}"

      - name: Attest Container Image @ Docker
        uses: actions/attest-build-provenance@v2
        id: attest
        if: "!contains(needs.metadata.outputs.release_version, '-SNAPSHOT')"
        with:
          subject-name: docker.io/chrisruffalo/taverna
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Attest Container Image @ Quay
        uses: actions/attest-build-provenance@v2
        id: attest_quay
        if: "!contains(needs.metadata.outputs.release_version, '-SNAPSHOT')"
        with:
          subject-name: quay.io/chrisruffalo/taverna
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  release_to_central:
    name: "Release to Maven Central"
    runs-on: ubuntu-latest
    # waits for all builds to complete so artifacts are all verified before trying to release
    needs: [metadata, test, build, build_native]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install GPG Secret Key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Set release version
        run: mvn -B versions:set -DnewVersion="${{ needs.metadata.outputs.release_version }}"

      - name: Publish to Maven Central
        # until snapshot publishing is fixed, just skip it
        if: "!contains(needs.metadata.outputs.release_version, '-SNAPSHOT')"
        run: mvn -B -DpreparePublish -DpublishCentral -DskipTests clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  update_release_with_links:
    name: "Update/Finalize Release"
    runs-on: ubuntu-latest
    needs: [metadata,release_to_central,update_release,update_release,container_image,build_native_operator]
    permissions:
      contents: write
    steps:
      - name: "Add Attestation URLs"
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.metadata.outputs.release_name }}
          tag_name: ${{ needs.metadata.outputs.release_tag }}
          body: |
            ## Attestations
            
            [Artifacts](${{ needs.update_release.outputs.artifact_attestation_url }})
            [Binary Docker Image](${{ needs.container_image.outputs.image_attestation_url }})
          append_body: true

      - name: "Add Maven URLs to Release"
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.metadata.outputs.release_name }}
          tag_name: ${{ needs.metadata.outputs.release_tag }}
          body: |
            ## Maven Artifacts
            
            |module|group|artifactId|version|
            |------|-----|----------|-------|
            |[taverna](https://central.sonatype.com/artifact/io.github.chrisruffalo/taverna/${{ needs.metadata.outputs.release_version }}/overview)|io.github.chrisruffalo|taverna|${{ needs.metadata.outputs.release_version }}|
            |[taverna cmd](https://central.sonatype.com/artifact/io.github.chrisruffalo/taverna-cmd/${{ needs.metadata.outputs.release_version }}/overview)|io.github.chrisruffalo|taverna-cmd|${{ needs.metadata.outputs.release_version }}|
            |[taverna maven plugin](https://central.sonatype.com/artifact/io.github.chrisruffalo/taverna-maven-plugin/${{ needs.metadata.outputs.release_version }}/overview)|io.github.chrisruffalo|taverna-maven-plugin|${{ needs.metadata.outputs.release_version }}|
          append_body: true

      - name: "Add Container URLs to Release"
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.metadata.outputs.release_name }}
          tag_name: ${{ needs.metadata.outputs.release_tag }}
          body: |
            ## Container Image
            [Docker Hub](https://hub.docker.com/layers/chrisruffalo/taverna/${{ needs.metadata.outputs.image_tag }}/images/${{ needs.container_image.outputs.image_digest }})
          append_body: true